// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9x2BuvbzTvfDLRz9gXpjfNBNNG7M7_A4',
    appId: '1:780514438687:web:ef1e20d352623272956f2a',
    messagingSenderId: '780514438687',
    projectId: 'movaapp-d0b9b',
    authDomain: 'movaapp-d0b9b.firebaseapp.com',
    storageBucket: 'movaapp-d0b9b.appspot.com',
    measurementId: 'G-FMLCR0NMN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvX51WPdWk6Rfu_q4uj8s08NnOwiNmtrU',
    appId: '1:780514438687:android:6a558a54fd686f51956f2a',
    messagingSenderId: '780514438687',
    projectId: 'movaapp-d0b9b',
    storageBucket: 'movaapp-d0b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdeE6oPXihEKI7dlF0bci-dIjoNRdMeg',
    appId: '1:780514438687:ios:f233dd5946a05eef956f2a',
    messagingSenderId: '780514438687',
    projectId: 'movaapp-d0b9b',
    storageBucket: 'movaapp-d0b9b.appspot.com',
    iosClientId: '780514438687-j8ond0jt7mve4k9ko45l0b5dlm1852df.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesAppFlutter',
  );
}
